combinationalmotifs/urls.py
from django.contrib import admin
from django.urls import path, include

import core.urls

urlpatterns = [

    # Apps
    path('', include('core.urls')),

    # Admin
    path('admin/', admin.site.urls),

]

core/urls.py
# Django
from django.urls import path

# Views
from core.views import IndexView, ContinuousModeView, ContinuousModeResolutionView, ResultView, UserRegisterView, UserLoginView, UserLogoutView

app_name = 'core'

urlpatterns = [
    
    # Rotas
    path('',  IndexView.as_view(), name='index'),
    path('login/',  UserLoginView.as_view(), name='login'),
    path('logout/',  UserLogoutView.as_view(), name='logout'),
    path('register/',  UserRegisterView.as_view(), name='register'),
    path('continuous/',  ContinuousModeView.as_view(), name='continuous-mode'),
    path('continuous/<int:pk>/', ContinuousModeResolutionView.as_view(), name='continuous-mode-resolution'),
    path('result/', ResultView.as_view(), name='result'),

]

core/models.py
# Django
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone

# Dango Packages
from treebeard.ns_tree import NS_Node

# Combinational Motifs
from core.managers import CustomUserManager

class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(max_length=100, unique=True, verbose_name='Username')
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'username'
    objects = CustomUserManager()

    def __str__(self):
        return self.username


class Motif(NS_Node):

    name = models.CharField(max_length=500, verbose_name='Motif name')
    start = models.IntegerField(verbose_name='Start index')
    stop = models.IntegerField(verbose_name='Stop index')

    class Meta:
        verbose_name = 'Motif'
        verbose_name_plural = 'Motifs'
    
    def __str__(self):
        return str(self.name)
    
class Diagram(models.Model):

    motif = models.ForeignKey('core.Motif', related_name='motifs', on_delete=models.PROTECT, verbose_name='Motif')
    index = models.IntegerField(verbose_name='Index')

    class Meta:
        verbose_name = 'Diagram'
        verbose_name_plural = 'Diagrams'
    
    def __str__(self):
        return f'{self.motif.name} - Diagram {self.index}'

class Resolution(models.Model):

    diagram = models.ForeignKey('core.Diagram', related_name='diagrams', on_delete=models.PROTECT, verbose_name='Diagram')
    user = models.ForeignKey('core.User', related_name='users', on_delete=models.PROTECT, verbose_name='User')
    date = models.DateTimeField(default=timezone.now, verbose_name='Date')
    success = models.BooleanField(verbose_name='Success')

    class Meta:
        verbose_name = 'Resolution'
        verbose_name_plural = 'Resolutions'
    
    def __str__(self):
        return f'{self.diagram} - Success: {self.success}'

core/forms.py
# Django
from django import forms

# Combinational Motifs
from core.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

core/views.py
# Django
from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, TemplateView, View, FormView


# Combinational Motifs
from core.forms import UserForm
from core.models import Motif, Diagram, User, Resolution

class IndexView(FormView):

    template_name = 'core/index.html'
    form_class = AuthenticationForm

class UserRegisterView(FormView):

    template_name = 'core/register.html'
    form_class = UserForm

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            user = User.objects.create_user(username=form.cleaned_data.get('username'), password=form.cleaned_data.get('password'))
            login(request=self.request, user=user, backend='django.contrib.auth.backends.ModelBackend')
            return HttpResponseRedirect(reverse_lazy('core:index'))
        else:
            return self.form_invalid(form)

class UserLoginView(LoginView):

    form_class = AuthenticationForm

class UserLogoutView(LogoutView):
    pass

class ContinuousModeView(LoginRequiredMixin, TemplateView):

    template_name = 'core/continuous.html'

    def get_context_data(self, **kwargs):
        context = super(ContinuousModeView, self).get_context_data(**kwargs)

        context['motifs'] = Motif.objects.all()

        return context

class ContinuousModeResolutionView(LoginRequiredMixin, DetailView):

    context_object_name = 'diagram'
    model = Diagram
    template_name = 'core/resolution.html'

    def get_context_data(self, **kwargs):
        context = super(ContinuousModeResolutionView, self).get_context_data(**kwargs)

        return context

class ResultView(LoginRequiredMixin, View):

    def post(self, *args, **kwargs):
        user = User.objects.get(pk=self.request.POST.get('user'))
        diagram = Diagram.objects.get(pk=self.request.POST.get('diagram'))
        result = self.request.POST.get('result')

        if result == 'success':
            success = True
        else:
            success = False

        Resolution.objects.create(user=user, diagram=diagram, success=success)

        return HttpResponse(result)

combinationalmotifs/templates/base.html
{% load static %}

<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>Combinational Motifs</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/tabler.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/combinational-motifs.css' %}" rel="stylesheet"/>
  </head>
  <body>
    <div class="page">
      {% include 'sidebar.html' %}
      <div class="page-wrapper">
        <div class="page-header d-print-none">
          <div class="container-xl">
            {% block header %}
            {% endblock header %}
          </div>
        </div>
        <div class="page-body">
          <div class="container-xl">
            {% block content %}
            {% endblock content %}
          </div>
        </div>
      </div>
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/tabler.min.js' %}"></script>
    {% block javascript %}
    {% endblock javascript %}
  </body>
</html>

combinationalmotifs/templates/sidebar.html
{% load widget_tweaks %}

<aside class="navbar navbar-vertical navbar-expand-lg navbar-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="sidebar-menu">
      <ul class="navbar-nav me-3 ms-3 mt-3">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:index' %}">
            <span class="h2">
              Index
            </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:continuous-mode' %}">
            <span class="h2">
              Motifs
            </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">
            <span class="h2">
              Admin
            </span>
          </a>
        </li>
        {% if request.user.is_anonymous %}
        <li class="nav-item mt-2">
          <form id="login-form" method="post" action="{% url 'core:login' %}">
            {% csrf_token %}
            {% render_field form.username class="form-control text-black pr-3" placeholder=form.username.label %}
            {% render_field form.password class="form-control text-black pr-3 mt-2" placeholder="Password" type="password" %}
          </form>
          <button class="btn btn-block btn-primary mt-2" type="submit" form="login-form">
            Login
          </button>
          <a href="{% url 'core:register' %}">
            <button class="btn btn-block btn-success mt-2 w-100">
              Register
            </button>
          </a>
        </li>
        {% else %}
        <li class="nav-item mt-2">
          <span class="h6">Logged as</span>
          <input type="text" class="form-control" name="example-disabled-input" value="{{ request.user.username }}" disabled>
          <form id="logout-form" method="post" action="{% url 'core:logout' %}">
            {% csrf_token %}
          </form>
          <button class="btn btn-block btn-yellow mt-2" type="submit" form="logout-form">
            Logout
          </button>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</aside>

core/templates/core/continuous.html
{% extends 'base.html' %}
{% load core_tags %}

{% block header %}
<div class="row g-2 align-items-center">
  <div class="col">
    <span class="h1">
      Select a Diagram
    </span>
  </div>
</div>
{% endblock header %}

{% block content %}
<div class="row row-deck row-cards">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        {% for motif in motifs %}
        {% get_diagrams motif=motif as diagrams %}
          <div class="row">
            <div class="col-auto ">
              <span class="h2 nivel-{{ motif.depth }}">{{ motif }}</span>
            </div>
            {% for diagram in diagrams %}
            {% get_result diagram_pk=diagram.pk user_pk=user.pk as result %}
            <div class="col-auto">
              {% if result == None %}
              <a href="{% url 'core:continuous-mode-resolution' pk=diagram.pk %}">
                <button class="btn btn-primary" style="width: 30px; height: 35px; margin-left: 10px; margin-bottom: 10px;">
                  {{ diagram.index }}
                </button>
              </a>
              {% elif result == True %}
              <a href="{% url 'core:continuous-mode-resolution' pk=diagram.pk %}">
                <button class="btn btn-success" style="width: 30px; height: 35px; margin-left: 10px; margin-bottom: 10px;">
                  {{ diagram.index }}
                </button>
              </a>
              {% elif result == False %}
              <a href="{% url 'core:continuous-mode-resolution' pk=diagram.pk %}">
                <button class="btn btn-danger" style="width: 30px; height: 35px; margin-left: 10px; margin-bottom: 10px;">
                  {{ diagram.index }}
                </button>
              </a>
              {% endif %}
            </div>
            {% endfor %}
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

core/templates/core/index.html
{% extends 'base.html' %}

{% block header %}
<div class="row g-2 align-items-center">
  <div class="col">
    <span class="h1">
      Combinational Motifs
    </span>
  </div>
</div>
{% endblock header %}

{% block content %}
<div class="row row-deck row-cards">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        {% if request.user.is_anonymous %}
        Welcome to Combinational Motifs. A Python implementation of the book by Maxim Blokh.
        {% else %}
        <b>{{ request.user|capfirst }}</b>, welcome to Combinational Motifs. A Python implementation of the book by Maxim Blokh.
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

core/templates/core/register.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block header %}
<div class="row g-2 align-items-center">
  <div class="col">
    <span class="h1">
      Register
    </span>
  </div>
</div>
{% endblock header %}

{% block content %}
<div class="row row-deck row-cards">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <form id="register-form" method="post" action="{% url 'core:register' %}">
          {% csrf_token %}
          {% render_field form.username class="form-control text-black pr-3" placeholder=form.username.label %}
          {% render_field form.password class="form-control text-black pr-3 mt-2" placeholder="Password" type="password" %}
        </form>
        <button class="btn btn-block btn-success mt-2" type="submit" form="register-form">
          Register
        </button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

core/templates/core/resolution.html
{% extends 'base.html' %}
{% load static %}
{% load core_tags %}

{% block header %}
<div class="row g-2 align-items-center">
  <div class="col">
    {% for motif in diagram.motif.get_ancestors %}
    <span class="h1 nivel-{{ motif.depth }}">{{ motif }}</span>
    </br>
    {% endfor %}
    <span class="h1 nivel-{{ diagram.motif.depth }}">{{ diagram.motif }}</span>
  </div>
</div>
{% endblock header %}

{% block content %}
<div class="alert alert-success alert-dismissible" role="alert" id="result-alert" hidden>
  <div class="d-flex">
    <div>
      <h4 class="alert-title">Resultado registrado com sucesso</h4>
    </div>
  </div>
  <a class="btn-close" data-bs-dismiss="alert" aria-label="close"></a>
</div>
<div class="row row-deck row-cards">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <div class="row align-center">
          <img src="{% static '/diagrams/' %}{{ diagram.pk}}.png" alt="{{ diagram.motif }}" style="max-width: 40%; height: auto; margin: 0 auto;" id="diagram">
          <img src="{% static '/answers/' %}{{ diagram.pk}}.png" alt="{{ diagram.motif }}" style="max-width: 50%; height: 50%; margin: 0 auto;" id="answer" hidden>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row row-deck row-cards mt-2">
  <div class="col-12">
    <div class="card">
      <div class="card-body m-0">
        <div class="row align-center">
          <div class="col-2">
            <button class="btn btn-lg btn-primary" onclick="showAnswer();">
              Show answer
            </button>
          </div>
          <div class="col-8 text-center">
            <button class="btn btn-lg btn-success" onclick="registerResolution('success');">
              Success
            </button>
            <button class="btn btn-lg btn-danger ms-3" onclick="registerResolution('error');">
              Error
            </button>
          </div>
          <div class="col-2">
            {% get_result diagram_pk=diagram.pk|add:1 user_pk=user.pk as result_next %}
            <a href="{% url 'core:continuous-mode-resolution' pk=diagram.pk|add:1 %}">
              {% if result_next == None %}
              <button class="btn btn-lg btn-primary float-end">
                Next
              </button>
              {% elif result_next == True %}
              <button class="btn btn-lg btn-success float-end">
                Next
              </button>
              {% elif result_next == False %}
              <button class="btn btn-lg btn-danger float-end">
                Next
              </button>
              {% endif %}
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block javascript %}
<script>

  // Answer
  function showAnswer() {
    let answer = document.getElementById('answer');
    answer.removeAttribute("hidden");
  }

  // Resolution
  function registerResolution(result) {

    $.ajax({
      type: "POST",
      url: "{% url 'core:result' %}",
      data: {
        csrfmiddlewaretoken: "{{ csrf_token }}",
        user: "{{ request.user.pk }}",
        diagram: "{{ diagram.pk }}",
        result: result
      },
      success: function (data) {
        let alert = document.getElementById('result-alert');
        alert.removeAttribute("hidden");
      }
    });
    
  }

</script>
{% endblock javascript %}